
bench:
  workload: retwis
  scale: 1
  weight:
    add_users: 5 
    follow: 15
    post_teet: 30
    get_timeline: 50
  population: # intial number of records in each table
    history: 1000000

schema: # table information
  - name: history
    column:
      - {name: h_key,     type: integer, primary: true}
      - {name: h_c_id,    type: integer}
#      - {name: h_c_d_id,  type: integer}
#      - {name: h_c_w_id,  type: integer}
#      - {name: h_d_id,    type: integer}
#      - {name: h_w_id,    type: integer}
#      - {name: h_date,    type: string}
#      - {name: h_amount,  type: double}
#      - {name: h_data,    type: string}

# sharding strategy.
# default is MOD by primary key.
# CUSTOM means strategy is defined in the code.
# TODO a better way to define sharding strategy.
sharding:
  history:    MOD
